default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: sensei
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: sensei_dev

test: &test
  <<: *default
  database: sensei_test

production:
  pool: 10
  reaping_frequency: 10
  reconnect: true
  url: <%= ENV['APPSDECK_POSTGRESQL_URL'] %>


cucumber:
  <<: *test
